apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: demo
spec:
  # Enable Kafka Exporter
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*
  entityOperator:
    topicOperator: {}
  kafka:
    config:
      auto.create.topics.enable: false
      default.replication.factor: 3
      delete.topic.enable: false
      min.insync.replicas: 2
    listeners:
      - name: internal
        port: 9092
        tls: false
        type: internal
      # Add load balancer listener. Note: port must be unique
      - name: loadblancer
        port: 9093
        tls: false
        type: loadbalancer
    replicas: 3
    storage:
      type: persistent-claim
      size: 10G
      deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      deleteClaim: true
      size: 1Gi
      type: persistent-claim