apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-demo
spec:
  secretName: kafka.tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - '*.example.com'